enabled_locales: ["en"]
user:
  max_name_size: 50
  max_email_size: 255
  min_password_size: 6
  avatar_profile: 200

book:
  book_size: 130x150
  per_page: 20

blogs:
  per_page: 10
  avatar_comment: 50
  per_page: 20

admin:
  book:
    image_size: 50
    page_index: 1
    per_page: 20
  user_table:
    size: "120x140"
  user:
    per_page: 20
books:
  show:
    sizel: 200x250
    sizes: 130x140
header:
  size: "1000x400"
